server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TESTDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
